id: I1D4D1126
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T21:20:30+00:00'
last_modified: '2022-06-09T07:49:43.907676+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ873
  title: སྒྲོལ་བསྟོད་རྣམ་བཤད་རབ་གསལ་མེ་ལོང་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '6006':
      image_group_id: I1CZ946
      title: Volume 1 of sgrol bstod rnam bshad rab gsal me long
      total_pages: 32
      order: 1
      base_file: 6006.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
