id: P007944
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ873
  title: སྒྲོལ་བསྟོད་རྣམ་བཤད་རབ་གསལ་མེ་ལོང་
  author: ''
  volumes:
    a4ddd4f04a5d4301aaca5792c13b0000:
      image_group_id: I1CZ946
      title: Volume 1 of sgrol bstod rnam bshad rab gsal me long
      volume_number: 1
      total_pages: 32
      base_file: v001.txt
ebook_metadata:
  title: སྒྲོལ་བསྟོད་རྣམ་བཤད་རབ་གསལ་མེ་ལོང་
  author: ''
  sku: P007944
  cover: cover.jpg
  layers:
  - pagination
