id: P007944
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ873
  title: སྒྲོལ་བསྟོད་རྣམ་བཤད་རབ་གསལ་མེ་ལོང་
  author: ''
  volumes:
    deb8f3b9af974149873a9aed19315650:
      image_group_id: I1CZ946
      title: ''
      volume_number: 1
      total_pages: 32
ebook_metadata:
  title: སྒྲོལ་བསྟོད་རྣམ་བཤད་རབ་གསལ་མེ་ལོང་
  author: ''
  sku: P007944
  cover: cover.jpg
  layers:
  - pagination
